### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by varun-karandikar30** [sunxm2357/TwoStreamVAN#1]
It been nearly 3 months since the initial estimated date of code upload. 
![Screenshot from 2020-04-16 16-38-24](https://user-images.githubusercontent.com/14979526/79449369-b861e480-8000-11ea-9201-b587222c2528.png)

Authors please do not make claims about code availability in your paper when the repository is totally empty.

**Comment by sunxm2357** [comment]
Thanks for your interest in our paper. I have already pushed the code and README will be updated soon. Feel free to try out the code. Sorry for the delay!

**Comment by varun-karandikar30** [comment]
Thanks for the really prompt response. I am interested in the idea proposed in your paper for Video generation problem. The implementation will surely help in understanding the paper better.
Thanks again and Cheers!!
